### ISSUE TITLE
上传某些文件时,post的信息会出现不一样..

### ISSUE THREAD

**Issue by daofeng2015** [wxy1343/aliyunpan#11]
![image](https://user-images.githubusercontent.com/14891398/114534563-b8cba480-9c81-11eb-8e88-d9bccdf95d75.png)
这个下面的hash是怎么得来的呢?
api为:https://api.aliyundrive.com/v2/file/create

**Comment by wxy1343** [comment]
可能是随机生成的sha1

**Comment by wxy1343** [comment]
![image](https://user-images.githubusercontent.com/49909001/114594580-fe0ec700-9cbf-11eb-8670-c4ec95d95cdf.png)

**Comment by wxy1343** [comment]
pre_hash是文件前1KiB的sha1
```r
$ dd if=1 of=2 bs=1024 count=1
1+0 records in
1+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 0.0009015 s, 1.1 MB/s
$ sha1sum 2
19e16be6a9fb8ba6849a4a8e7513353c12b4f6c0  2
```
