### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by daofeng2015** [wxy1343/aliyunpan#12]
![image](https://user-images.githubusercontent.com/14891398/114883574-a2674980-9e37-11eb-8499-9594cbde2a31.png)

**Comment by pongfcnkl** [comment]
refresh_token？

**Comment by daofeng2015** [comment]
> refresh_token？

我已经新建文件了,里面也写入了refresh_token的值

**Comment by pongfcnkl** [comment]
> 
> 
> > refresh_token？
> 
> 我已经新建文件了,里面也写入了refresh_token的值
main.py里面16行代码改一下
              default='config/aliyunpan.yaml', show_default=True)
