### ISSUE TITLE
希望能加入去重

### ISSUE THREAD

**Issue by Zhaodaidai** [wxy1343/aliyunpan#14]
没有去重有点不方便

**Comment by Zhaodaidai** [comment]
希望加个能选择上传到哪个目录

**Comment by wxy1343** [comment]
> 没有去重有点不方便

可能你需要强制覆盖
 指令     |参数          |描述                 |
 --------|------------|----------------|
upload | -f, --force | 强制覆盖文件|

**Comment by wxy1343** [comment]
> 希望加个能选择上传到哪个目录

用法: main.py upload [可选参数] [文件路径] [指定上传到的目录]

**Comment by Zhaodaidai** [comment]
原来有啊 感谢!
&nbsp;

file:///C:/Users/%E5%B0%8F%E4%B9%96%E4%B9%96/Desktop/3350.gif


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月17日(星期六) 中午1:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wxy1343/aliyunpan] 希望能加入去重 (#14)





  
希望加个能选择上传到哪个目录
  
用法: main.py upload [可选参数] [文件路径] [指定上传到的目录]
