### ISSUE TITLE
作者你好！我使用你的源码把pyinstaller 产出物放到了我的下载站上，readme.md 注明了出处

### ISSUE THREAD

**Issue by cooluc** [wxy1343/aliyunpan#16]
https://media.cooluc.com/source/aliyunDrive-cli

你边是否允许使用我们这种途径分享 aliyunpan-cli 的成果？如不允许这种途径分享我会将它删除

**Comment by wxy1343** [comment]
可以的

**Comment by wxy1343** [comment]
感谢分享
