### ISSUE TITLE
上传大文件会连接错误

### ISSUE THREAD

**Issue by Aquaakuma** [wxy1343/aliyunpan#17]

**Comment by Aquaakuma** [comment]
一直这样
```
[*][upload]D:\bangumi\派遣战斗员！\4\[NC-Raws] 戰鬥員派遣中！ - 04 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4
3秒后重试
```
好像说是SSL有问题，连接不上，暂时没法调试，不知道断点要打哪里，一直循环重试

**Comment by Aquaakuma** [comment]
core.py 243行给r赋值的时候返回201，然后就抛出错误跳出try了

**Comment by wxy1343** [comment]
请提供异常的类型

**Comment by Zhaoxixiangchu** [comment]
此问题在windows上直接运行main去上传并未复现，在Centos7上能够复现  ConnectionError，代码出异常捕获应该是RequestException的。  一会再centos上加日志具体看看错误信息

**Comment by Aquaakuma** [comment]
![image](https://user-images.githubusercontent.com/31891793/116024635-3976a180-a681-11eb-9edd-17400def8f7d.png)
如图，快速上传没问题，上传文件会出现。

**Comment by Zhaoxixiangchu** [comment]
> ![image](https://user-images.githubusercontent.com/31891793/116024635-3976a180-a681-11eb-9edd-17400def8f7d.png)
> 如图，windows上：快速上传没问题，上传文件会出现。
> 还有这个
> ![image](https://user-images.githubusercontent.com/31891793/116025124-552e7780-a682-11eb-8a7a-fefa7852071c.png)

老哥 你的这个文件方便给我发一份试试么  我在pycharm上并没有复现该问题，  Python版本为3.7.4

**Comment by Zhaoxixiangchu** [comment]
> ![image](https://user-images.githubusercontent.com/31891793/116024635-3976a180-a681-11eb-9edd-17400def8f7d.png)
> 如图，windows上：快速上传没问题，上传文件会出现。
> 还有这个
> ![image](https://user-images.githubusercontent.com/31891793/116025124-552e7780-a682-11eb-8a7a-fefa7852071c.png)

![image](https://user-images.githubusercontent.com/49143126/116034802-7bf6a900-a696-11eb-823c-73e3739c51aa.png)


![image](https://user-images.githubusercontent.com/49143126/116034864-97fa4a80-a696-11eb-9509-6a0b07a41f2b.png)
  
由于打的断点所以速度显示的有问题 (忽略这个问题)

**Comment by Aquaakuma** [comment]
> > ![image](https://user-images.githubusercontent.com/31891793/116024635-3976a180-a681-11eb-9edd-17400def8f7d.png)
> > 如图，windows上：快速上传没问题，上传文件会出现。
> > 还有这个
> > ![image](https://user-images.githubusercontent.com/31891793/116025124-552e7780-a682-11eb-8a7a-fefa7852071c.png)
> 
> ![image](https://user-images.githubusercontent.com/49143126/116034802-7bf6a900-a696-11eb-823c-73e3739c51aa.png)
> 
> ![image](https://user-images.githubusercontent.com/49143126/116034864-97fa4a80-a696-11eb-9509-6a0b07a41f2b.png)
> 
> 由于打的断点所以速度显示的有问题 (忽略这个问题)

[aliyunpan.zip](https://github.com/wxy1343/aliyunpan/files/6377122/aliyunpan.zip)
虚拟环境和代码打包发你了

**Comment by ceabqw** [comment]
我也遇到了
环境:python3.9
debian10
上传文件：13G左右

**Comment by wxy1343** [comment]
把出异常的类型都捕获了应该可以解决

**Comment by Aquaakuma** [comment]
还是SSL连接错误，即使捕获了异常，但是和aliyun的连接还是出错，所有一直都是重试

**Comment by wxy1343** [comment]
> 还是SSL连接错误，即使捕获了异常，但是和aliyun的连接还是出错，所以一直都是重试

重新上传还是SSL错误吗

**Comment by Aquaakuma** [comment]
对，不是ssl错误就是连接超时，进度都是0，可能是阿里那边改了什么吧，等更多人反馈看看。

**Comment by wxy1343** [comment]
> 对，不是ssl错误就是连接超时，进度都是0，可能是阿里那边改了什么吧，等更多人反馈看看。

可能和网络或系统环境有关，建议更换后重试

**Comment by Aquaakuma** [comment]
> > 对，不是ssl错误就是连接超时，进度都是0，可能是阿里那边改了什么吧，等更多人反馈看看。
> 
> 可能和网络或系统环境有关，建议更换后重试

搜索了下，可能要把request设置为verify=false，之后测试一下

**Comment by wxy1343** [comment]
> > > 对，不是ssl错误就是连接超时，进度都是0，可能是阿里那边改了什么吧，等更多人反馈看看。
> > 
> > 
> > 可能和网络或系统环境有关，建议更换后重试
> 
> 搜索了下，可能要把request设置为verify=false，之后测试一下

默认就是不[验证](https://github.com/wxy1343/aliyunpan/blob/73fd940249af9eda1dcba05eeb9d51eeb1d87ec8/aliyunpan/api/req.py#L12)的

**Comment by chen-7-c** [comment]
window上传没问题 centos7服务器上尝试了下连接失败不停重复3s

**Comment by wxy1343** [comment]
指令 | 参数 | 描述
-- | -- | --
upload | -t, --time-out | 分块上传超时时间(秒)

出现此问题可以把超时时间设置大一点
