### ISSUE TITLE
access token   expire

### ISSUE THREAD

**Issue by d7185540** [wxy1343/aliyunpan#18]
请问使用什么办法更新access token，使用login方法没用。

**Comment by wxy1343** [comment]
使用[get_access_token](https://github.com/wxy1343/aliyunpan/blob/37b78126c0df62c5025e612f72470387220ad346/aliyunpan/api/core.py#L290)生成器更新，需要先设置refresh_token
```python3
from aliyunpan.api.core import AliyunPan

if __name__ == '__main__':
    disk = AliyunPan()
    disk.refresh_token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    print(disk.access_token)
```
