### ISSUE TITLE
文件上传失败

### ISSUE THREAD

**Issue by 821938089** [wxy1343/aliyunpan#22]
文件大小：7G
我在完成文件上传的post那里print了一下r.json()
输出内容：{'code': 'InvalidParameter.ContentHash', 'message': 'The input parameter content_hash is not valid. file content hash is not matched with content_hash in complete file request'}
debug模式日志文件：[aliyunpan.zip](https://github.com/wxy1343/aliyunpan/files/6573020/aliyunpan.zip)

**Comment by wxy1343** [comment]
重新上传还这样吗
别的文件可以上传吗

**Comment by 821938089** [comment]
> 重新上传还这样吗
> 别的文件可以上传吗

重新上传也是失败
别的小一点的可以，大的死都不行

感觉遇到了玄学的问题
测试如下：
3G上传成功x1
3.8G上传成功x1
5.2G上传失败x3（没有成功过）
7G上传失败x3（没有成功过）

你上传大文件有没有出现问题啊？

**Comment by wxy1343** [comment]
可能是上传大文件有概率出现**400 Bad Request**就会出现上传失败

**Comment by 821938089** [comment]
似乎发现问题了，最后一个分块上传会失败，错误代码是403
感觉不是概率问题，是必然会出现的，大一点的文件我传了这么多次就没一次成功过
![image](https://user-images.githubusercontent.com/8674809/120402969-e4136b80-c375-11eb-9c7e-958d89ba69b0.png)

11556是最后一片分块

**Comment by 821938089** [comment]
似乎知道是什么原因了，最后一块分片的上传链接的有效期很短，只有一个小时，导致上传时间超过一小时的文件都会失败。

**Comment by wxy1343** [comment]
感谢反馈

**Comment by 821938089** [comment]
又出现的新的问题了
![image](https://user-images.githubusercontent.com/8674809/120498275-ae13cd00-c3f1-11eb-9e79-abb3e6049bbb.png)

状态代码400

分块现在好像有上限了，最多10000，需要调整分块上传的默认大小

顺便说一下https://github.com/wxy1343/aliyunpan/blob/main/aliyunpan/api/core.py#L364
这里的raise用法有误，因为上下文没有异常，raise又没有参数，会引发RuntimeError异常

**Comment by 821938089** [comment]
又发现一些问题

使用-cs参数调大了分块大小后，会出现Issues #17的问题，这是因为你代码里写的5秒超时不够用，如果5秒内分块无法完成上传，就会超时抛异常。

需要给request设置read timeout为None之类的，让他永不超时。
或者直接设置整个timeout为None。
参考：https://docs.python-requests.org/en/master/user/advanced/#timeouts

**Comment by wxy1343** [comment]
> 又发现一些问题
> 
> 使用-cs参数调大了分块大小后，会出现Issues #17的问题，这是因为你代码里写的5秒超时不够用，如果5秒内分块无法完成上传，就会超时抛异常。
> 
> 需要给request设置read timeout为None之类的，让他永不超时。
> 或者直接设置整个timeout为None。
> 参考：https://docs.python-requests.org/en/master/user/advanced/#timeouts

![image](https://user-images.githubusercontent.com/49909001/120534265-386d2880-c414-11eb-8965-d778b2f47612.png)
一直以为这个timeout是和服务器建立tcp连接的时间
之前用func_timeout来解决超时也忘记考虑这个参数的作用
put请求只有在上传完当前分块才会返回数据，这个时间超过5秒就会报错
出现的错误SSLError和ConnectionError之类一时半会也没往超时上想
不过还是感谢你的提醒才让我发现这个错误

**Comment by wxy1343** [comment]
> 又出现的新的问题了
> ![image](https://user-images.githubusercontent.com/8674809/120498275-ae13cd00-c3f1-11eb-9e79-abb3e6049bbb.png)
> 
> 状态代码400
> 
> 分块现在好像有上限了，最多10000，需要调整分块上传的默认大小
> 
> 顺便说一下https://github.com/wxy1343/aliyunpan/blob/main/aliyunpan/api/core.py#L364
> 这里的raise用法有误，因为上下文没有异常，raise又没有参数，会引发RuntimeError异常

增加PartNumberOverLimit异常类型，指定参数chunk_size超出限制就会抛出
默认不传参数chunk_size时如果超出限制会自动计算一个合适的大小
增加BadResponseCode异常类型用来替代响应代码≠200时的RuntimeError异常

**Comment by 821938089** [comment]
还是有问题

上传链接过期刷新好像没有效果

依然会报{'code': 'InvalidParameter.ContentHash', 'message': 'The input parameter content_hash is not valid. file content hash is not matched with content_hash in complete file request'}

详细看日志文件：[aliyunpan.zip](https://github.com/wxy1343/aliyunpan/files/6591198/aliyunpan.zip)
直接拉到最后那里

**Comment by 821938089** [comment]
![image](https://user-images.githubusercontent.com/8674809/120637183-22f21000-c4a1-11eb-9f65-70d5acf40af5.png)

上传过程中出现了这个，这个没debug版的日志，不知道是啥问题导致的。

**Comment by wxy1343** [comment]
> ![image](https://user-images.githubusercontent.com/8674809/120637183-22f21000-c4a1-11eb-9f65-70d5acf40af5.png)
> 
> 上传过程中出现了这个，这个没debug版的日志，不知道是啥问题导致的。

应该是之前的分块没上传成功导致的

**Comment by wxy1343** [comment]
> ![image](https://user-images.githubusercontent.com/8674809/120637183-22f21000-c4a1-11eb-9f65-70d5acf40af5.png)
> 
> 上传过程中出现了这个，这个没debug版的日志，不知道是啥问题导致的。

我看了日志刷新完后上传响应的代码是200，应该是上传成功了才对

**Comment by wxy1343** [comment]
> 还是有问题
> 
> 上传链接过期刷新好像没有效果
> 
> 依然会报{'code': 'InvalidParameter.ContentHash', 'message': 'The input parameter content_hash is not valid. file content hash is not matched with content_hash in complete file request'}
> 
> 详细看日志文件：[aliyunpan.zip](https://github.com/wxy1343/aliyunpan/files/6591198/aliyunpan.zip)
> 直接拉到最后那里

我看了日志刷新完后上传响应的代码是200，应该是上传成功了才对

**Comment by 821938089** [comment]
> > 还是有问题
> > 上传链接过期刷新好像没有效果
> > 依然会报{'code': 'InvalidParameter.ContentHash', 'message': 'The input parameter content_hash is not valid. file content hash is not matched with content_hash in complete file request'}
> > 详细看日志文件：[aliyunpan.zip](https://github.com/wxy1343/aliyunpan/files/6591198/aliyunpan.zip)
> > 直接拉到最后那里
> 
> 我看了日志刷新完后上传响应的代码是200，应该是上传成功了才对

我发现了，你的上传逻辑有问题啊，分块有647个，现在才传了473个分块就发complete请求了。

**Comment by wxy1343** [comment]
> > > 还是有问题
> > > 上传链接过期刷新好像没有效果
> > > 依然会报{'code': 'InvalidParameter.ContentHash', 'message': 'The input parameter content_hash is not valid. file content hash is not matched with content_hash in complete file request'}
> > > 详细看日志文件：[aliyunpan.zip](https://github.com/wxy1343/aliyunpan/files/6591198/aliyunpan.zip)
> > > 直接拉到最后那里
> > 
> > 
> > 我看了日志刷新完后上传响应的代码是200，应该是上传成功了才对
> 
> 我发现了，你的上传逻辑有问题啊，分块有647个，现在才传了473个分块就发complete请求了。

是我粗心大意了，[#L392](https://github.com/wxy1343/aliyunpan/blob/5a0212b4fa506d6edd9c5d08b716c3409f2644fe/aliyunpan/api/core.py#L392)多传了个参数part_number，导致只返回了当前分块到最后一个分块的part_info_list

**Comment by 821938089** [comment]
> > ![image](https://user-images.githubusercontent.com/8674809/120637183-22f21000-c4a1-11eb-9f65-70d5acf40af5.png)
> > 上传过程中出现了这个，这个没debug版的日志，不知道是啥问题导致的。
> 
> 应该是之前的分块没上传成功导致的

这好像是同一个问题导致的，上传链接过期刷新后，新的part_info_list有问题，导致上传分块错位。

**Comment by wxy1343** [comment]
> > > ![image](https://user-images.githubusercontent.com/8674809/120637183-22f21000-c4a1-11eb-9f65-70d5acf40af5.png)
> > > 上传过程中出现了这个，这个没debug版的日志，不知道是啥问题导致的。
> > 
> > 
> > 应该是之前的分块没上传成功导致的
> 
> 这好像是同一个问题导致的，上传链接过期刷新后，新的part_info_list有问题，导致上传分块错位。

应该是的，等会我修改一下调试看看
