### ISSUE TITLE
文件上传失败

### ISSUE THREAD

**Issue by toolor** [wxy1343/aliyunpan#26]
`ali u . movie `
上上个版本正常
命令执行出错如下：
![20210604235656.png](https://7.dusays.com/2021/06/04/d4e5c9ac1b81c.png)

**Comment by wxy1343** [comment]
发下debug日志看看

**Comment by wxy1343** [comment]
![image](https://user-images.githubusercontent.com/49909001/120832421-39789400-c593-11eb-9a81-0a72955ee118.png)
应该是aliyunpan.log上传失败了，原因是文件内容变化了导致上传的文件hash不匹配，新版加了对该异常的抛出
