### ISSUE TITLE
调用多次ls枚举目录后开始抛异常

### ISSUE THREAD

**Issue by 821938089** [wxy1343/aliyunpan#27]
我是通过from aliyunpan.cli.cli import Commander来初始化并调用文件操作函数
我刚开始的几次ls的调用时没问题的，但是几次之后就开始一直报错，我尝试调试了下也不知道问题在哪（其实是看不懂）
报错如图
![image](https://user-images.githubusercontent.com/8674809/120891959-240c7400-c63e-11eb-9cd3-e53f6b87ffd0.png)
日志里面混进去了一些我打的log：[日志.zip](https://github.com/wxy1343/aliyunpan/files/6602578/default.zip)
我写的上传相关的代码FileUpload.py，其中upload方法是通过启动线程调用的
[FileUpload.zip](https://github.com/wxy1343/aliyunpan/files/6602590/FileUpload.zip)
部分改过的地方
![image](https://user-images.githubusercontent.com/8674809/120892713-37214300-c642-11eb-8178-edceac0c6caf.png)
![image](https://user-images.githubusercontent.com/8674809/120892790-8798a080-c642-11eb-9e6b-ae13d288c251.png)
![image](https://user-images.githubusercontent.com/8674809/120892805-941cf900-c642-11eb-8bc0-d6439ebe5671.png)

**Comment by wxy1343** [comment]
应该是[创建文件](https://github.com/wxy1343/aliyunpan/blob/f185ba0994483b4b39cd8817e2b2922dd57783f7/aliyunpan/cli/cli.py#L155)少传了个data参数
```python
self._path_list._tree.create_node(tag=path.name, identifier=file_id, parent=parent_file_id,
                                              data=FileInfo(name=path.name, type=False))
```
