### ISSUE TITLE
请问大佬能不能加入站内分享功能

### ISSUE THREAD

**Issue by LittleTurtle2333** [wxy1343/aliyunpan#29]
直接分享出可以让用户在浏览器能直接打开的链接
比如：https://www.aliyundrive.com/s/jDaRVPZ5C6d

**Comment by LittleTurtle2333** [comment]
因为我自己的Python开发水平能力有限

**Comment by wxy1343** [comment]
这个要等阿里云开放分享功能了才行，暂时没有可以分享的账号来测试

**Comment by LittleTurtle2333** [comment]
@wxy1343 我可以把我的账号借给你，除了有分享功能，还有别人没有的压缩包分享权限

**Comment by wxy1343** [comment]
可以啊，如果方便的话，可以留个联系方式私聊

**Comment by LittleTurtle2333** [comment]
微信：rm_-rf_
