### ISSUE TITLE
aliyunpan.log的问题

### ISSUE THREAD

**Issue by toolor** [wxy1343/aliyunpan#31]
你好开发者，aliyunpan.log和task.yaml能不能在~固定的目录生成？我把此cli工具是我主要生产力工具，问题是，我在那里运行命令，在哪一个目录都会生成aliyunpan.log文件。

**Comment by wxy1343** [comment]
https://github.com/wxy1343/aliyunpan/blob/29d74d917c990872f1b82022ac1bd837d0e5d259/aliyunpan/api/utils.py#L16
修改为
```python3
from pathlib import Path

ROOT_DIR = Path('~').expanduser().as_posix()
```
