### ISSUE TITLE
关于安装与登录的建议

### ISSUE THREAD

**Issue by yanght1001** [wxy1343/aliyunpan#39]
1、安装
能否把程序提交到python的官方程序库，使用
`pip install aliyunpan  `
这样的命令安装，同时安装的时候处理好依赖库，让安装更加简单。
2、登录
使用命令tokenlogin 用token登录；
示例：
`python main.py tokenlogin  'tokenidxxxxxxxxxxxxxxxxxxxxxxxxxxx'`

使用命令login 用户名和密码登录；
`python main.py login  username password`

感谢大神，支持大神。。。。。。期待大神。。

**Comment by wxy1343** [comment]
感谢支持

**Comment by wxy1343** [comment]
> 1、安装
> 能否把程序提交到python的官方程序库，使用
> `pip install aliyunpan `
> 这样的命令安装，同时安装的时候处理好依赖库，让安装更加简单。
> 2、登录
> 使用命令tokenlogin 用token登录；
> 示例：
> `python main.py tokenlogin 'tokenidxxxxxxxxxxxxxxxxxxxxxxxxxxx'`
> 
> 使用命令login 用户名和密码登录；
> `python main.py login username password`
> 
> 感谢大神，支持大神。。。。。。期待大神。。

token登录
`python main.py -t xxx`

账号密码登录
`python main.py -u xxx -p xxx`
