### ISSUE TITLE
好像阿里云盘更新了秒传接口了，本地文件验证HASH后不能秒传

### ISSUE THREAD

**Issue by linker999** [wxy1343/aliyunpan#47]
我测试了一下，本地文件验证HASH后不能秒传（阿里云盘是有这个文件的！）

**Comment by wxy1343** [comment]
秒传不行了，必须要获取文件随机的8个字节才能秒传，也就是没有文件就没法秒传
### 解决方法：
* 可以分享秒传链接的时候带上文件直链，这种方法由于直链的有效期只有4小时所以局限较大

**Comment by linker999** [comment]
> 秒传不行了，必须要获取文件随机的8个字节才能秒传，也就是没有文件就没法秒传
> 
> ### 解决方法：
> * 可以分享秒传链接的时候带上文件直链，这种方法由于直链的有效期只有4小时所以局限较大

本地上传也不行哦，不能秒传，盘上面有这个文件的、

**Comment by wxy1343** [comment]
> > 秒传不行了，必须要获取文件随机的8个字节才能秒传，也就是没有文件就没法秒传
> > ### 解决方法：
> > 
> > * 可以分享秒传链接的时候带上文件直链，这种方法由于直链的有效期只有4小时所以局限较大
> 
> 本地上传也不行哦，不能秒传，盘上面有这个文件的、

代码还没更新

**Comment by linker999** [comment]
> > > 秒传不行了，必须要获取文件随机的8个字节才能秒传，也就是没有文件就没法秒传
> > > ### 解决方法：
> > > 
> > > * 可以分享秒传链接的时候带上文件直链，这种方法由于直链的有效期只有4小时所以局限较大
> > 
> > 
> > 本地上传也不行哦，不能秒传，盘上面有这个文件的、
> 
> 代码还没更新

恩恩 都说是秒传接口变了

**Comment by exexue** [comment]
大佬，更新后使用你的最新版2.7.11还是无法妙传本地文件，已经在网盘上存在了的文件，以前可以的，阿里修改接口后，听说只是不能空传验证上传，问题是我用实实在在的本地文件还是得重新开始传，不能秒传。提示如下


root@debian:/data/Downloads# aliyunpan upload Unfaithful.2002.1080p.BrRip.x264.BOKUTOX.YIFY.mp4 /
[*][hash]Unfaithful.2002.1080p.BrRip.x264.BOKUTOX.YIFY.mp4
[+][hash]Unfaithful.2002.1080p.BrRip.x264.BOKUTOX.YIFY.mp4
[*][upload]Unfaithful.2002.1080p.BrRip.x264.BOKUTOX.YIFY.mp4
upload... [**********] 0.64% 139.39KB/s^C
Aborted!

本地文件上传验证完成hash后，还是会重新传，不会秒传。。大佬，求解决。

**Comment by wxy1343** [comment]
> 大佬，更新后使用你的最新版2.7.11还是无法妙传本地文件，已经在网盘上存在了的文件，以前可以的，阿里修改接口后，听说只是不能空传验证上传，问题是我用实实在在的本地文件还是得重新开始传，不能秒传。提示如下
> 
> root@debian:/data/Downloads# aliyunpan upload Unfaithful.2002.1080p.BrRip.x264.BOKUTOX.YIFY.mp4 /
> [_][hash]Unfaithful.2002.1080p.BrRip.x264.BOKUTOX.YIFY.mp4 [+][hash]Unfaithful.2002.1080p.BrRip.x264.BOKUTOX.YIFY.mp4 [_][upload]Unfaithful.2002.1080p.BrRip.x264.BOKUTOX.YIFY.mp4
> upload... [**********] 0.64% 139.39KB/s^C
> Aborted!
> 
> 本地文件上传验证完成hash后，还是会重新传，不会秒传。。大佬，求解决。

暂时只支持秒传分享和导入，文件上传的还没搞
