### ISSUE TITLE
更新新版本2.7.11依旧不能秒传本地文件

### ISSUE THREAD

**Issue by exexue** [wxy1343/aliyunpan#48]
大佬，刚才更新后使用你的最新版2.7.11还是无法妙传本地文件，已经在网盘上存在了的文件，以前可以的，阿里修改接口后，听说只是不能空传验证上传，问题是我用实实在在的本地文件还是得重新开始传，不能秒传。提示如下

root@debian:/data/Downloads# aliyunpan upload Unfaithful.2002.1080p.BrRip.x264.BOKUTOX.YIFY.mp4 /
[*][hash]Unfaithful.2002.1080p.BrRip.x264.BOKUTOX.YIFY.mp4
[+][hash]Unfaithful.2002.1080p.BrRip.x264.BOKUTOX.YIFY.mp4
[*][upload]Unfaithful.2002.1080p.BrRip.x264.BOKUTOX.YIFY.mp4
upload... [**********] 0.64% 139.39KB/s^C
Aborted!

本地文件上传验证完成hash后，还是会重新传，不会秒传。。大佬，求解决。

**Comment by wxy1343** [comment]
暂时只支持秒传分享和导入，文件上传的还没搞
