### ISSUE TITLE
2.7.14上传一直失败

### ISSUE THREAD

**Issue by yayaleslie** [wxy1343/aliyunpan#50]
大佬，2.7.13上传是可以秒传的
更新到2.7.14不行了
![image](https://user-images.githubusercontent.com/19268555/133612387-eff5875b-f602-434a-b39f-1e69fff1fd86.png)

**Comment by yayaleslie** [comment]
本地回滚到 2.7.13就可以，除了会多出部分错误
![image](https://user-images.githubusercontent.com/19268555/133614305-603d09a7-50c1-40c1-9c56-996ccf2fd208.png)

**Comment by wxy1343** [comment]
[v2.7.14](https://github.com/wxy1343/aliyunpan/commit/ba42a3c4027c7378af45f547b77bbacf98bd019e)只加了个try，并没有修改秒传功能

**Comment by yayaleslie** [comment]
应该网络哪有问题，现在是OK的，感谢大佬
