### ISSUE TITLE
请求增加自动重试

### ISSUE THREAD

**Issue by LittleTurtle2333** [wxy1343/aliyunpan#6]
上传一半老是卡着不动

**Comment by wxy1343** [comment]
已更新

**Comment by LittleTurtle2333** [comment]
> 已更新

还是无法自动重试，我指的是上传中的卡住。![Video_20210314_083507_777.gif](https://user-images.githubusercontent.com/32336368/111068838-5d34bc80-8505-11eb-9b51-13792fe7f549.gif)

**Comment by wxy1343** [comment]
那只能说你网络不好，有在上传速度很慢，修改了一下，上传时间过长就会自动重试

**Comment by LittleTurtle2333** [comment]
> 那只能说你网络不好，有在上传速度很慢，修改了一下，上传时间过长就会自动重试

不不不，不是的，我把WiFi关了测的，不会自动重试

**Comment by LittleTurtle2333** [comment]
> 那只能说你网络不好，有在上传速度很慢，修改了一下，上传时间过长就会自动重试

我觉得可以每分钟检测一次当前百分比，如果和上次的百分比一样就重新上传

**Comment by wxy1343** [comment]
> > 那只能说你网络不好，有在上传速度很慢，修改了一下，上传时间过长就会自动重试
> 
> 不不不，不是的，我把WiFi关了测的，不会自动重试

![image](https://user-images.githubusercontent.com/49909001/111073026-0edce900-8518-11eb-92fd-7494242bb5ac.png)
WIFI关了会自动重试啊

**Comment by LittleTurtle2333** [comment]
> > > 那只能说你网络不好，有在上传速度很慢，修改了一下，上传时间过长就会自动重试
> > 
> > 
> > 不不不，不是的，我把WiFi关了测的，不会自动重试
> 
> ![image](https://user-images.githubusercontent.com/49909001/111073026-0edce900-8518-11eb-92fd-7494242bb5ac.png)
> WIFI关了会自动重试啊

试了刚刚发的最新的，可以了

**Comment by LittleTurtle2333** [comment]
还是有卡住的情况，下面跟着3句1秒后重试。

**Comment by LittleTurtle2333** [comment]
@wxy1343 能不能增加重试3次后重新开始，天翼云的cli有这个功能

**Comment by wxy1343** [comment]
> @wxy1343 能不能增加重试3次后重新开始，天翼云的cli有这个功能

可以了
