### ISSUE TITLE
到底如何配置、配置文件

### ISSUE THREAD

**Issue by sw586** [wxy1343/aliyunpan#67]
echo "refresh_token: 'xxxxx'"  >  ~/.config/aliyunpan.yaml
这个是在linux上我知道，

说实话配置文件这部分，写的有点不清楚，当然应该是我的问题，我想说有点魔幻~~

在window下我是如下操作的：

1、我的电脑右键配置环境变量：
ALIYUNPAN_CONF 配置文件路径
ALIYUNPAN_ROOT 根目录(log和tasks输出路径)

2、在C:\Users\sw\Desktop\aliyunpan-main\config
下新建aliyunpan.yaml
填入：refresh_token: 'XXX'

3启动：

python main.py -c C:\Users\sw\Desktop\aliyunpan-main\config\aliyunpan.yaml
![image](https://user-images.githubusercontent.com/24788222/143617751-138bf35c-6817-4625-b97c-e0bd78966bb9.png)

麻烦指点下哪里错了

**Comment by wxy1343** [comment]
win配置默认在C:\Users\用户名\.config\aliyunpan.yaml
错误看提示缺少命令
> python main.py 选项(可选) 命令(必须) 参数(可选)
