### ISSUE TITLE
下载文件夹时文件不完整

### ISSUE THREAD

**Issue by chenweiwen07** [wxy1343/aliyunpan#68]
### 问题
使用aliyunpan download下载文件夹时，发现云盘中的文件夹深度超过3就不下载了。

### 描述
比如，云盘中存在目录`/tmp/a/b/c/d/e`，每层目录都一个1.txt文件，执行`aliyunpan download /tmp/a`命令，下载后的文件目录只到`/tmp/a/b/c`，`/tmp/a/b/c/d`文件夹就没有下载，期间也没有报错。

**Comment by wxy1343** [comment]
<html>
<body>


-d, --depth | 文件递归深度
-- | --



</body>
</html>

**Comment by chenweiwen07** [comment]
@wxy1343 感谢感谢，一下子就解决问题了 👍
