### ISSUE TITLE
上传总是显示上传超时

### ISSUE THREAD

**Issue by xiaochenchui** [wxy1343/aliyunpan#70]

**Comment by wxy1343** [comment]
<html>
<body>


-T, --timeout | 请求超时时间(秒)
-- | --



</body>
</html>

<html>
<body>


upload,sync | -t, --time-out | 分块上传超时时间(秒)
-- | -- | --



</body>
</html>

**Comment by xiaochenchui** [comment]
> -T, --timeout	请求超时时间(秒)
> upload,sync	-t, --time-out	分块上传超时时间(秒)

加了超时时间后可以开始上传，但是每秒十多kb是什么原因呢，服务器是腾讯云香港的

**Comment by wxy1343** [comment]
> > -T, --timeout	请求超时时间(秒)
> > upload,sync	-t, --time-out	分块上传超时时间(秒)
> 
> 加了超时时间后可以开始上传，但是每秒十多kb是什么原因呢，服务器是腾讯云香港的

限速了吧
