### ISSUE TITLE
v3.0.1 版本不工作

### ISSUE THREAD

**Issue by sbwml** [wxy1343/aliyunpan#74]
此 264887694821418870cfacc5dbcf2de8bc32b3e7 提交后，releases 文件不再工作 https://github.com/wxy1343/aliyunpan/releases/tag/v3.0.1-2c82286

测试平台：Windows 10

[
![1](https://user-images.githubusercontent.com/16485166/147260684-5379135b-46ec-46f5-93e9-f8ef9b00f1a0.png)
](url)

**Comment by wxy1343** [comment]
这个应该是pyinstaller的bug
当存在如下目录结构时打包后无法运行
```bash
$ tree .
.
├── test
│   └── __init__.py
└── test.py

1 directory, 2 files
$ cat test.py
print('test')
$ pyinstaller -F test.py
...
$ dist/test
$ 
$ rm -rf build dist test.spec test/__init__.py
$ pyinstaller -F test.py
...
$ dist/test
test
$ 
```

**Comment by wxy1343** [comment]
本项目打包命令
```pyinstaller -F aliyunpan/main.py -n aliyunpan-cli```
