### ISSUE TITLE
在win下应该如何使用呢?

### ISSUE THREAD

**Issue by SeasonG-CN** [wxy1343/aliyunpan#81]
**aliyunpan-cli.exe --refresh-token "xxxx" 会提示Error: Missing command.
aliyunpan-cli.exe --refresh-token 'xxxx' 也不行
aliyunpan-cli.exe -t 也不行
到底怎么运行呢.......能给个具体参考吗?
--refresh-token 不行
-t 不行
--refresh_token 也不行
--refresh-token 后面应该怎么填?
config文件能不能改到当前路径例如 .\.config\aliyunpan.yaml**

**Comment by SeasonG-CN** [comment]
**能不能给个win下的使用文档?**

**Comment by wxy1343** [comment]
单指定参数无法运行，需要加上命令，例如`aliyunpan-cli -t xxx ls`
使用局部配置文件仅需在运行目录下建立`aliyunpan.yaml`，需要配置全局时可以放到`~\.config\aliyunpan.yaml`
