### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by hahahawin** [wxy1343/aliyunpan#9]
![image](https://user-images.githubusercontent.com/47048329/112749073-8750a900-8ff2-11eb-8fa2-c2752349321b.png)

**Comment by wxy1343** [comment]
更新下python版本试试

**Comment by imldy** [comment]
> 更新下python版本试试

你好，需要哪个版本……麻烦明确说一下

**Comment by imldy** [comment]
> > 更新下python版本试试
> 
> 你好，需要哪个版本……麻烦明确说一下

python3.7可用

**Comment by wxy1343** [comment]
> > 更新下python版本试试
> 
> 你好，需要哪个版本……麻烦明确说一下

https://docs.python.org/3.7/library/collections.html#collections.namedtuple
由于namedtuple的default参数在3.7才加入，所以低于3.7的可以手动修改[**代码**](https://github.com/wxy1343/aliyunpan/blob/main/aliyunpan/api/type.py)
```python3
FileInfo = namedtuple('FileInfo', _file_info, defaults=('',) * len(_file_info))
UserInfo = namedtuple('UserInfo', ['id', 'nick_name', 'ctime', 'phone', 'drive_id'], defaults=('',) * 5)
```
变成
```python3
FileInfo = namedtuple('FileInfo', _file_info)
FileInfo.__new__.__defaults__ = ('',) * len(_file_info)
UserInfo = namedtuple('UserInfo', ['id', 'nick_name', 'ctime', 'phone', 'drive_id'])
UserInfo.__new__.__defaults__ = ('',) * 5
```

**Comment by imldy** [comment]
@wxy1343 好的，谢谢，感谢回复
