### ISSUE TITLE
秒传大文件速度较慢

### ISSUE THREAD

**Issue by irockstar** [wxy1343/aliyunpan#93]
你好！

我通过 share 命令获取秒传文件链接，然后通过 upload -s 上传。

小文件没问题，大文件（7.8G）会出现进程一直不结束，内存持续增加的情况。

在阿里云盘 web 端看到文件已经上传成功，并且可以在线播放。

![WX20220726-173533](https://user-images.githubusercontent.com/1676743/180977153-eb7df113-25e5-459e-9229-2be2d1c4c935.png)

![WX20220726-173514](https://user-images.githubusercontent.com/1676743/180977126-72fbd8ab-156f-4681-ba66-b3846580ec8a.png)

![WX20220726-173850](https://user-images.githubusercontent.com/1676743/180977176-31ce98aa-ef98-458a-97f0-849b5a664bf1.png)

**Comment by wxy1343** [comment]
-s参数指定的是序列文件，带了-s参数还会解析文件里是否有秒传链接

**Comment by irockstar** [comment]
搞定了

aliyunpan share -s  与 aliyunpan upload -s 配合使用，超级棒！感谢！

![image](https://user-images.githubusercontent.com/1676743/181416933-bea7b239-4287-48e1-8b31-c00d4026d582.png)

**Comment by irockstar** [comment]
问题已解决

**Comment by irockstar** [comment]
问题已解决🙏
