### ISSUE TITLE
大佬，是否可以添加一个 http 代理的支持？

### ISSUE THREAD

**Issue by sbwml** [wxy1343/aliyunpan#95]
是这么的一个应用场景，我有在 GitHub Actions 使用 aliyunpan-cli，但是最近的 GitHub Actions 的网络相当的差，文件经常上传超时，因为每个runner 都有执行时长限制，被上传文件如果过大就没办法让它以很低的速度去完成上传操作了。
https://github.com/sbwml/builder/runs/8051584658?check_suite_focus=true#step:11:739

如果加入 http 代理支持，就可以自行找个服务器做中继来解决 github actions 到 阿里云盘 的网络问题了。

**Comment by wxy1343** [comment]
你可以使用proxychains-ng来代理
```shell
sudo apt update && sudo apt install proxychains-ng
echo -e "[ProxyList]\nhttp [ip] [port]" > proxychains.conf
proxychains4 -f proxychains.conf python3 xxx.py
```

**Comment by sbwml** [comment]
> 

是好用的！
